plugin:
    name: 'arkylus.stockmanagement::lang.plugin.name'
    description: 'arkylus.stockmanagement::lang.plugin.description'
    author: Arkylus
    icon: oc-icon-bar-chart
    homepage: 'http://arkylus.com/stockmanagement'
permissions:
    arkylus.stockmanagement.manage_item:
        tab: 'arkylus.stockmanagement::lang.plugin.name'
        label: 'arkylus.stockmanagement::lang.item.manage'
    arkylus.stockmanagement.dashboard:
        tab: 'arkylus.stockmanagement::lang.plugin.name'
        label: 'arkylus.stockmanagement::lang.plugin.dashboard'
    arkylus.stockmanagement.manage_stock:
        tab: 'arkylus.stockmanagement::lang.plugin.name'
        label: 'arkylus.stockmanagement::lang.plugin.manage_stock'
    'arkylus.stockmanagement.*':
        tab: 'arkylus.stockmanagement::lang.plugin.name'
        label: 'arkylus.stockmanagement::lang.plugin.admin'
    arkylus.stockmanagement.manage_location:
        tab: 'arkylus.stockmanagement::lang.plugin.name'
        label: 'arkylus.stockmanagement::lang.plugin.manage_location'
navigation:
    dashboard:
        label: 'arkylus.stockmanagement::lang.plugin.name'
        url: arkylus/stockmanagement/dashboard
        icon: icon-stock
        iconSvg: plugins/arkylus/stockmanagement/assets/images/stockmanagement-icon.svg
        permissions:
            - arkylus.stockmanagement.dashboard
            - arkylus.stockmanagement.manage_item
            - arkylus.stockmanagement.manage_stock
        sideMenu:
            items:
                label: 'arkylus.stockmanagement::lang.plugin.items'
                url: arkylus/stockmanagement/items
                icon: icon-list
                permissions:
                    - arkylus.stockmanagement.manage_item
                    - arkylus.stockmanagement.manage_stock
            adjustment:
                label: 'arkylus.stockmanagement::lang.plugin.adjustment'
                url: arkylus/stockmanagement/stock
                icon: icon-database
                permissions:
                    - arkylus.stockmanagement.manage_stock
            manage_location:
                label: 'arkylus.stockmanagement::lang.plugin.manage_location'
                url: arkylus/stockmanagement/location
                icon: icon-map-marker
                permissions:
                    - arkylus.stockmanagement.manage_location

            manage_user_location:
                label: 'arkylus.stockmanagement::lang.plugin.manage_user_location'
                url: arkylus/stockmanagement/userlocation
                icon: icon-user               
