title: Stock
modelClass: Arkylus\Stockmanagement\Models\Stock
list: $/arkylus/stockmanagement/models/stock/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '30'
showSetup: false
showCheckboxes: false
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
