title: Items
modelClass: Arkylus\Stockmanagement\Models\Item
list: $/arkylus/stockmanagement/models/item/columns.yaml
recordUrl: 'arkylus/stockmanagement/items/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: false
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
